default_language_version:
  python: python3.9
  
repos:
  - repo: https://github.com/python-poetry/poetry
    rev: 1.1.13
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements.txt", "--without-hashes"]
        
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: [--max-complexity=15, --max-line-length=80]

  - repo: https://github.com/google/yapf
    rev: v0.32.0
    hooks:
      - id: yapf
        args: [--style="pep8", --in-place]